### ISSUE TITLE
Support import directive that is valid JavaScript

### ISSUE THREAD

**Issue by ghost** [ecm4u/ecm4u-alfresco-bugpatches#3]
Proposed by Benjamin K.

Clean, extensible import API for JavaScript resources https://issues.alfresco.com/jira/browse/ACE-2722

The problem is that the import syntax for Web Scripts is not valid Javascript. This causes problems for people who use IDEs or with syntax validation checkers.

As a reminder, the current syntax is:

```
<import resource="classpath:/alfresco/templates/org/alfresco/import/alfresco-util.js">
```

Axel proposes two alternatives:

```
importScript("legacy", "classpath:/alfresco/templates/webscripts/org/alfresco/repository/forms/pickerresults.lib.js", true);

importScript("classpath:/alfresco/templates/org/alfresco/import/alfresco-util.js", true);
```

Others propose simply allowing the import to still work when commented out:

```
//<import resource="classpath:/alfresco/templates/org/alfresco/import/alfresco-util.js">
```

or

```
//+<import resource="classpath:/alfresco/templates/org/alfresco/import/alfresco-util.js">
```

The last comment in the bug is:

>    Ok - the confusion may be due to the fact that there are two distinct  implementation of ScriptResourceHelper in Alfresco - one in Surf and    one on Repository tier. The Surf one has been fixed and the change is    in both 5.0.d and 5.0.1. The Repository tier one has not been changed / adapted.

So it's already been accepted into Alfresco, but only in Surf. Should
this repo accept this patch so code analysis can operate over more of
the source?

**Comment by AFaust** [comment]
Only the "commented import directive support" has been accepted into Surf. Any import API is still a far cry from being added to Alfresco.

**Comment by ghost** [comment]
@AFaust Do you consider this proposal to fix a bug? I understand that it is a nuisance but it does not acually break anyhting in Alfresco. Besides, IDEs support filtering of such unwanted errors.

**Comment by AFaust** [comment]
I consider this to be a major nuisance, but not a bug. That's also reflected in the type of ticket I reported (for some reason Mark Rogers was retroactively set as the reporter). There are file structuring approaches that can be used to avoid the associated syntax errors even in IDEs that don't support suppression, i.e. my *.(get|post).js often only consist of imports to *.lib.js while those don't contain any import.

I personally would not try to address this as part of a "bugfix" addon.

**Comment by ghost** [comment]
I agree. We should keep this in mind for a different module.

**Comment by AFaust** [comment]
In my Nashorn engine module I have included AMD-style module loading to avoid any need for explicit import statements.

**Comment by support-crius-group-com** [comment]
Trick to keep IntelliJ from going bananas.

```
<import resource="/Company Home/Data Dictionary/Scripts/lib/crius-utils.js">
//</import>
```

If the tag is closed the validation at least checks the syntax. It can't resolve, but happier code and alfresco does seem to run it without issues.
